spring:
  config:
    activate:
      on-profile: default
  flyway:
    enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL8Dialect
          storage_engine: innodb
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      cors:
        allowed-methods: '*'
        exposed-headers: Content-Disposition
        allowed-origins:
          - http://localhost:3000
          - http://localhost:8080
          - http://localhost:8081

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

debug: false
